# Copyright 2019 Tricot Inc.
# Use of this source code is governed by the license in the LICENSE file.

version: 2
jobs:
  build:
    docker:
      - image: tricot/build-public-circleci:1.7.1

    working_directory: ~/xsp

    steps:
      - checkout

      # Restore bazel cache:
      - restore_cache:
          keys:
          - v2-cache-{{ .Revision }}
          - v2-cache-

      # Sync external deps:
      - run: .circleci/sync_deps.sync

      # Build everything:
      - run: |
          source .circleci/envsetup.sh
          .circleci/build_all.sh

      # Save bazel cache:
      # TODO(vtl): Also cache build directories?
      - save_cache:
          paths:
            - ~/downloads
            - ~/esp-idf
            - ~/xtensa-esp32-elf
          key: v2-cache-{{ .Revision }}
