# Copyright 2019 Tricot Inc.
# Use of this source code is governed by the license in the LICENSE file.

version: 2
jobs:
  build:
    docker:
      - image: tricot/build-public-circleci:1.3.1

    working_directory: ~/xsp

    steps:
      - checkout

      # Restore bazel cache:
      - restore_cache:
          keys:
          - v1-cache-{{ .Revision }}
          - v1-cache-

      # Sync external deps:
      - run: .circleci/sync_deps.sync

      # CMake:
      - run:
          working_directory: examples/ws_client
          command: |
            source ~/xsp/.circleci/envsetup.sh
            idf.py build

      # Save bazel cache:
      # TODO(vtl): Also cache build directories?
      - save_cache:
          paths:
            - ~/esp-idf
            - ~/xtensa-esp32-elf
          key: v1-cache-{{ .Revision }}
