# Copyright 2019 Tricot Inc.
# Use of this source code is governed by the license in the LICENSE file.

PROJECT_NAME := xsp-atomic8-test
EXTRA_COMPONENT_DIRS := ../../components

include $(IDF_PATH)/make/project.mk
